emoji_dict = {
    '??' : 'https://i.imgur.com/8PMqsKT.gif',
    '!!' : 'https://i.imgur.com/16XMEvr.gif',
    '...' : 'https://i.imgur.com/AiHlCm3.gif',
    '그래요' : 'https://i.imgur.com/ghvguCP.gif',
    '그렇군요' : 'https://i.imgur.com/cAj6pWj.gif',
    '나빴어' : 'https://i.imgur.com/uaOaVr4.gif',
    '너무해요' : 'https://i.imgur.com/hy6ji2a.gif',
    '눈이감겨요' : 'https://i.imgur.com/x1NnXbj.gif',
    '도와줘요' : 'https://i.imgur.com/z0XxoaI.gif',
    '됐어요' : 'https://i.imgur.com/eCJWqzf.gif',
    '두려워요' : 'https://i.imgur.com/hevO5W7.gif',
    '먹을만하네요' : 'https://i.imgur.com/32lcVy5.gif',
    '모르겠어요' : 'https://i.imgur.com/GmwyZo5.gif',
    '뭐해요' : 'https://i.imgur.com/J28Udvs.gif',
    '뭘봐요' : 'https://i.imgur.com/a250Yg7.gif',
    '뭘원하나요' : 'https://i.imgur.com/Uel6Flg.gif',
    '미안해요' : 'https://i.imgur.com/uoZnuWt.gif',
    '반가워요' : 'https://i.imgur.com/xKaNQJ2.gif',
    '배고파요' : 'https://i.imgur.com/S3gVyOw.gif',
    '뱃속에고기가있어요' : 'https://i.imgur.com/FvDP3MN.gif',
    '변태' : 'https://i.imgur.com/eEvh0WO.gif',
    '부끄러워요' : 'https://i.imgur.com/DUeMLLR.gif',
    '사랑해요' : 'https://i.imgur.com/XVU2zgH.gif',
    '숨을래요' : 'https://i.imgur.com/cR5N9gr.gif',
    '싫은데요' : 'https://i.imgur.com/yC7iJ1E.gif',
    '안아줘요' : 'https://i.imgur.com/FUX3i7q.gif',
    '알겠어요' : 'https://i.imgur.com/ukTsfvX.gif',
    '애애앵' : 'https://i.imgur.com/NTyZj6X.gif',
    '앨랠래' : 'https://i.imgur.com/usGTQs8.gif',
    '어지러워요' : 'https://i.imgur.com/ogmXwoV.gif',
    '어쩌라는거야' : 'https://i.imgur.com/2ASRyEf.gif',
    '왜요' : 'https://i.imgur.com/UIPFyrf.gif',
    '으아아앙' : 'https://i.imgur.com/nMxhu3E.gif',
    '이상해요' : 'https://i.imgur.com/GYcrdp6.gif',
    '잘자요' : 'https://i.imgur.com/2anCxXp.gif',
    '장난이에요' : 'https://i.imgur.com/K6SCdgF.gif',
    '저는기어다닐거예요' : 'https://i.imgur.com/njkECEV.gif',
    '정말고마워요' : 'https://i.imgur.com/0rcCHib.gif',
    '좋아해요' : 'https://i.imgur.com/mQgOeHJ.gif',
    '지금가요' : 'https://i.imgur.com/v1tART4.gif',
    '참잘했어요' : 'https://i.imgur.com/ZXxlWgr.gif',
    '축하해요' : 'https://i.imgur.com/fyBZkUu.gif',
    '칭찬해줘요' : 'https://i.imgur.com/BQKge8L.gif',
    '토닥여주세요' : 'https://i.imgur.com/J239tjd.gif',
    '푸하하' : 'https://i.imgur.com/5aiA92w.gif',
    '행복해요' : 'https://i.imgur.com/y7B3YSP.gif',
    '화났어요' : 'https://i.imgur.com/waGt98F.gif',
    '힘내요' : 'https://i.imgur.com/aRkIivp.gif'
}

emoji_names_mood = [
    '!!', '??', '눈이감겨요', '두려워요', 
    '모르겠어요', '미안해요', '반가워요', '배고파요', 
    '부끄러워요', '사랑해요', '어지러워요', '이상해요', 
    '장난이에요', '좋아해요', '행복해요', '화났어요',
]
emoji_names_answer = [
    '..', '그래요', '그렇군요', '나빴어',
    '너무해요', '됐어요', '먹을만하네요', '싫은데요',
    '알겠어요', '어쩌라는거야', '왜요', '정말고마워요',
    '지금가요', '참잘했어요', '축하해요', '푸하하'
]
emoji_names_say = [
    '도와줘요', '뭐해요', '뭘봐요', '뭘원하나요',
    '뱃속에고기가있어요', '변태', '숨을래요', '안아줘요',
    '애애앵', '앨랠래', '으아아앙', '잘자요',
    '저는기어다닐거예요', '칭찬해줘요', '토닥여주세요', '힘내요'
]